# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html
[registries.crates-io]
protocol = "sparse"

